# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(db_index=True, default=datetime.datetime(2020, 1, 11, 19, 53, 54, 385393), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 11, 19, 53, 54, 385393), verbose_name='Дата'),
        ),
    ]
